### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by nIKsL** [raelldottin/tachikoma#56]
Привет.
Скачал, поставил зависимости, запустил run.py
ввожу email\pass вылетает с обшибкой ('Email или пароль неверны.')
запускаю device.reset() повторяю процедуру. Меняю язык девайса :D
правильность ввода проверял несколько раз(вставлял через  copy\paste). 
Через сайт по ним авторизуется без проблем.

**Comment by raelldottin** [comment]
@nIKsL Это личный проект. Если вы собираетесь использовать, убедитесь, что вы используете Python версии 3.9.18. Я не ожидал, что смогу помочь другим использовать его. Это как бы создано для моих аккаунтов. И еще: ты агент КГБ и пытаешься подружиться со мной? 🤣

**Comment by nIKsL** [comment]
? :D не совсем понял посыл про агента ? 
хотел на досуге попилить через селениум простые автоматизашки, как всегда предварительно чекнул гитхаб и набрёл на твой проект. Подход через апи мне понравился больше. Хотел посмотреть как ты реализовал, покрутить немного, но что-то пошло не так. Либо апи поменяли.. либо ещё что...

**Comment by raelldottin** [comment]
@nIKsL Прошу прощения, это была неуместная шутка. Этот проект работает через действие GitHub. Он использует определенную версию Python, упомянутую ранее. Вы также можете найти более подробную информацию об API здесь: https://github.com/JThinkable/pixyship или https://github.com/solevis/pixyship. у них есть более полное использование API с веб-сайтом https://pixyship.com. Кроме того, вам также следует поискать исходный код для бота Discord Deloros. мой проект не очень хорошо документирован, и для его запуска требуется среднее знание Python.

**Comment by raelldottin** [comment]
@nIKsL Позже сегодня я напишу более качественную документацию, чтобы вы могли легко ее запустить, шаг за шагом следуя документации.

**Comment by raelldottin** [comment]
@nIKsL Я даже буду так любезен, что добавлю в код локализацию, чтобы вывод был и на русском языке, если он установлен в качестве языка по умолчанию для вашей ОС.

**Comment by nIKsL** [comment]
спасибо за ссылки.
На самом деле просто хотелось узнать работает ли это сейчас :)
пытался запускать отладку, отваливается на этапе авторизации. 
Где-то в этом проекте встречал ru версию клиента (device lang='ru'), поэтому и предположил, что вы русскоговорящий. Но, возможно, это просто был copy\paste из другого источника. If you are not native russian speaker - it`s ok with eng :)

**Comment by raelldottin** [comment]
@nIKsL  вы можете попробовать запустить код из исходного проекта: https://github.com/t1f7/pythonstarships, мой код более персонализирован для моих нужд.

**Comment by raelldottin** [comment]
@nIKsL Кроме того, это сообщение в блоге, которое я написал, объясняя, как я его расширил. Удачи и до свидания.
