### ISSUE TITLE
пример

### ISSUE THREAD

**Issue by nIKsL** [raelldottin/tachikoma#57]
спасибо, с ошибкой разобрался (была проблема со стороны моего ip)

можно пример config.secrets ?
изучаю код, но так будет быстрее :)

кстати, отличная работа!

**Comment by raelldottin** [comment]
@nIKsL 

# сервер жестко запрограммирован как smtp.gmail.com с портом 587 в строке 63
try:
        session = smtplib.SMTP("smtp.gmail.com", 587)
        session.ehlo()
        session.starttls()
        session.login(email, password)
        session.send_message(message)
        session.quit()
    except:
        logging.exception("Exception occurred", exc_info=True)

# config.secrets
[MAIL_CONFIG]
SENDER_EMAIL = your_email@mail.ru
SENDER_PASSWD = your_password
RECIPIENT_EMAIL = recipient_email@example.com

**Comment by nIKsL** [comment]
Понял. Я думал там ты хранишь данные клиентов.
При использовании с компьютера я могу ускорить постройку Макс на 12 часов. Тут, как я понимаю такой функции нет, т.к. код представляется как андроид клиент? И Макс ускорение на 5 последних минут? Ещё не нашёл апи для боя (как отправить в бой)/миссий.  Для дрона увидел, но пока не докачался, чтобы проверить :)

**Comment by raelldottin** [comment]
@nIKsL 

в прошлом году это сработало, но затем разработчики игры изменили серверный код, чтобы разрешить использовать конечные точки SpeedUpResearchUsingBoostGauge и SpeedUpRoomConstructionUsingBoostGauge только типам устройств, являющихся клиентами ПК или Mac. Мне так и не удалось найти обходной путь.

конечные точки битвы требуют контрольных сумм, я не использую конечные точки API, которым требуется контрольная сумма, потому что я думаю, что разработчики намеренно использовали для них контрольные суммы, чтобы предотвратить автоматизацию. файл sdk/security.py может дать вам подсказки о том, как взломать контрольную сумму. код Python как есть не бесит разработчиков. но если вы взломаете контрольную сумму, вас могут забанить.

**Comment by nIKsL** [comment]
а какая ситуация с рынком ? могу я продать вещь и потом забрать ресурсы из почты ?

**Comment by raelldottin** [comment]
@nIKsL 

Конечная точка /MessageService/ListActiveMarkplaceMessages5 используется для перечисления элементов торговой площадки.
Конечная точка /MarketService/Purchase4 используется для покупки товаров, для этой конечной точки требуется контрольная сумма.
Конечная точка /MessageService/CollectReward2 используется для сбора элементов из вашего почтового ящика.
Конечная точка /HistoryService/PriceHistory используется для получения истории цен на товар.
Конечная точка /MarketService/ListSalesByItemDesignId используется для сортировки продаваемых товаров.
Конечная точка /MarketService/SellItem используется для продажи предметов, для этой конечной точки требуется контрольная сумма.

Раньше контрольная сумма вычислялась следующим образом: hashlib.md5((deviceKey + email + ts + accessToken + salt + 'savysoda').encode('utf-8')).hexdigest().
Они изменили его, вам нужно будет перепроектировать приложение, чтобы выяснить, как они создают новую контрольную сумму.
У Microsoft есть проект GitHub, который большинство исследователей в области безопасности используют для обращения контрольных сумм, но я не могу вспомнить название проекта.

**Comment by nIKsL** [comment]
а как перезарядить мины ? мешки с песком ? купить ракеты ?
есть метод client.rebuildAmmo(), но он что-то не справляется

**Comment by raelldottin** [comment]
@nIKsL 
Конечная точка /RoomService/RebuildAmmo2 позволяет выполнить другую перестройку для None, которая предназначена для всех предметов, Ammo для предметов боеприпасов, Android для предметов комнаты Android, Craft для предметов комнаты вешалки, модулей для модулей комнаты и зарядов для ракет.
Это сработало в прошлом году, а в этом году к нему добавили контрольную сумму. Итак, я прекратил его использовать.
